version: '3'
services:
  postgres:
    image: postgres:10.6
    restart: always
    # Increase max_connections for better dev experience :)
    command: postgres -c 'max_connections=300'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
